version: '3.7'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: blog
    ports:
      - 3000:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ./__tests__:/app/__tests__
      - ./src:/app/src
      - ./pages:/app/pages
      - ./postsMd:/app/postsMd
      - ./public:/app/public
      - ./tsconfig.json:/app/tsconfig.json
      - ./next.config.js:/app/next.config.js
      - ./jest.config.js:/app/jest.config.js
      - ./jest.setup.js:/app/jest.seutp.js
      - ./types.d.ts:/app/types.d.ts
    tty: true
    stdin_open: true
    # command: yarn jest
    command: yarn dev
    # command: yarn analyze
    # command: yarn lint
    # command: bash -c "yarn build && yarn start"
